import fs from 'fs';

const htmlFiles = fs.readdirSync('.').filter(f => f.endsWith('.html'));

const categoryMap = {
  'pdf': '/pdf-tools.html',
  'image': '/image-tools.html',
  'converter': '/converter-tools.html',
  'qr': '/qr-tools.html',
  'text': '/text-tools.html',
  'developer': '/developer-tools.html',
  'color': '/color-tools.html',
  'utilities': '/utility-tools.html'
};

htmlFiles.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let changed = false;

  // Fix category-card
  const catRegex = /<article([^>]*class="[^"]*category-card[^"]*"[^>]*)data-category="([^"]+)"([^>]*)>([\s\S]*?)<\/article>/gi;
  if (catRegex.test(content)) {
    content = content.replace(catRegex, (match, p1, category, p3, innerHtml) => {
      const url = categoryMap[category] || `/${category}-tools.html`;
      // Ensure text-decoration: none and display: block if needed, but styling is probably handled by CSS. Let's just use <a>
      return `<a href="${url}"${p1}data-category="${category}"${p3}>${innerHtml}</a>`;
    });
    changed = true;
  }

  // Also fix feature-card in HTML if any (statically generated)
  // Actually, feature-cards are usually dynamically generated by JS, except maybe some hardcoded ones?
  const featRegex = /<article([^>]*class="[^"]*feature-card[^"]*"[^>]*)data-url="([^"]+)"([^>]*)>([\s\S]*?)<\/article>/gi;
  if (featRegex.test(content)) {
    content = content.replace(featRegex, (match, p1, url, p3, innerHtml) => {
      return `<a href="${url}"${p1}data-url="${url}"${p3}>${innerHtml}</a>`;
    });
    changed = true;
  }

  if (changed) {
    fs.writeFileSync(file, content);
  }
});
